Linter and a bunch of fixes
QubesOS/qubes-desktop-linux-menu pull request #1
Opened 2021-08-19 13:00 UTC by marmarta

Support for pylint and mypy , keynav, a bunch of fixes for issues found by mypy and pylint.

2021-08-19 13:01 UTC, marmarta commented
@marmarek , what is needed in this repo to make it run CI?

2021-08-19 13:10 UTC, marmarek commented
PipelineRetry

2021-08-19 13:13 UTC, marmarek commented
PipelineRetry

2021-08-23 21:03 UTC, marmarta commented
PipelineRetry

2021-08-25 15:36 UTC, marmarta commented
@marmarek , I'm adding tests now, but otherwise this is ready for a review.

2021-08-29 15:47 UTC, marmarek requested changes
Few more comments for parts unchanged in this PR:
 - `Makefile`: intsall icons into `hicolor` icon theme
 - `Makefile.builder`: `RPM_BUILD_DEFINES` should not be necessary
 - rpm spec: several dependencies are not needed here
 - `debian/copyright`: update author
 - `qubes-menu.glade~` should not be here

2021-08-29 15:47 UTC, marmarek commented on README.md
> +![](menu1.png)
Please place those files in some subdir.

2021-08-29 15:47 UTC, marmarek commented on debian/control
> - python3-qui,
This package should depend on `python3-qubes-menu`

2021-08-29 15:47 UTC, marmarek commented on debian/rules
> +	make install DESTDIR=debian/qubes-desktop-linux-menu/usr/bin/
`DESTDIR` should not include `/usr/bin`

2021-08-30 20:53 UTC, marmarta commented on qubes_menu/desktop_file_manager.py
> +        vm_name = entry.get('X-Qubes-VmName') or None
No, it returns an empty string

2021-08-30 22:09 UTC, marmarta commented
Changes made. Will add more tests in coming days, but otherwise this is ready to merge (if the build succeeds).

2021-08-31 21:32 UTC, marmarek approved these changes

2021-08-31 21:33 UTC, merged