WIP Search
QubesOS/qubes-desktop-linux-menu pull request #16
Opened 2022-10-13 13:58 UTC by marmarta

This is going to be search implementation based on initial @ninavizz design and further development by me. It is based on #15 because I want to avoid potential rebase hell.

2022-10-26 22:34 UTC, marmarta commented on qubes_menu/page_handler.py
> +    def initialize_page(self):
done

2022-10-27 14:37 UTC, marmarta commented
PipelineRetryFailed

2022-10-28 13:28 UTC, marmarta commented
Added screenshots to the readme, can see them here: https://github.com/marmarta/qubes-desktop-linux-menu/tree/search_alpha#search-pane

2022-10-28 14:01 UTC, marmarek requested changes

2022-10-28 14:15 UTC, marmarek commented
Regarding keyboard navigation:
 - when switching VM selection, an application from previous VM remain selected - this behaves funny regarding subsequent navigation on the apps pane (and also, pressing enter does launch what was selected before but now invisible)
 - it isn't clear if focus is on apps or VMs - fixing this by unselecting app when going to VMs pane may fix the previous point too
 - arrow up cannot switch back to the search bar - not sure if an issue, since typing anything does switch
 -

2022-10-28 14:38 UTC, marmarta commented
Fixed filter to be more resilient + fixed keyboard nav; left the "can't explicitly move focus to search bar" issue, if it turns out to be problematic in use, will return to change it.

2022-10-28 21:46 UTC, marmarek approved these changes

2022-10-28 21:47 UTC, merged