Improve keyboard navigation
QubesOS/qubes-desktop-linux-menu pull request #27
Opened 2023-03-01 12:57 UTC by marmarta

More predictable keynav from app list to vm list
Fix problem when someone is using keyboard and mouse at the same time.

2023-03-03 14:15 UTC, marmarta commented
Keyboard navigation is still unpredictable here :/

2023-03-07 16:57 UTC, marmarta commented
This is almost good now - but I still failed at wrangling the power button. I'll leave it as-is for now.

2023-04-10 00:13 UTC, marmarek requested changes
Keyboard navigation works for me only in the applications list (arrows up/down), but can't navigate other places (qubes list, main tabs etc) - nothing happens there.

I do see in logs a lot of `gtk_widget_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed`, I'm not sure if that's related.

2023-04-11 15:51 UTC, marmarta commented
> Keyboard navigation works for me only in the applications list (arrows up/down), but can't navigate other places (qubes list, main tabs etc) - nothing happens there.
> 
> I do see in logs a lot of `gtk_widget_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed`, I'm not sure if that's related.

I pushed a fix (hopefully).

2023-04-16 14:38 UTC, merged